export const COMMON_COLORS = [
  { value: "#ffffff", label: "white", className: "bg-white" },
  { value: "#f44336", label: "red", className: "bg-red-500" },
  { value: "#ff9800", label: "orange", className: "bg-orange-500" },
  { value: "#ffc107", label: "amber", className: "bg-amber-500" },
  { value: "#ffeb3b", label: "yellow", className: "bg-yellow-500" },
  { value: "#cddc39", label: "lime", className: "bg-lime-500" },
  { value: "#4caf50", label: "green", className: "bg-green-500" },
  { value: "#10b981", label: "emerald", className: "bg-emerald-500" },
  { value: "#009688", label: "teal", className: "bg-teal-500" },
  { value: "#00bcd4", label: "cyan", className: "bg-cyan-500" },
  { value: "#0ea5e9", label: "sky", className: "bg-sky-500" },
  { value: "#2196f3", label: "blue", className: "bg-blue-500" },
  { value: "#3f51b5", label: "indigo", className: "bg-indigo-500" },
  { value: "#8b5cf6", label: "violet", className: "bg-violet-500" },
  { value: "#9c27b0", label: "purple", className: "bg-purple-500" },
  { value: "#d946ef", label: "fuchsia", className: "bg-fuchsia-500" },
  { value: "#e91e63", label: "pink", className: "bg-pink-500" },
  { value: "#f43f5e", label: "rose", className: "bg-rose-500" },
  { value: "#64748b", label: "slate", className: "bg-slate-500" },
  { value: "#9e9e9e", label: "gray", className: "bg-gray-500" },
];
